version: '3'
services:
  nginx:
    volumes:
      - ./deploy/frontend/conf/nginx/cache-router.conf:/etc/nginx/conf.d/cache-router.conf
    links:
      - frontend
  frontend:
    image: scandipwa/frontend:${PROJECT_IMAGE}
    volumes:
      - core-frontend-data:/var/www/public
      - ./build/frontend/start-core.sh:/start-core.sh
    build:
      context: build/frontend
      args:
        - BASEPATH=${BASEPATH}
        - NODEJS_VERSION=${NODEJS_VERSION}
    working_dir: "/var/www/public"
    env_file: .env
    command: ["/bin/bash", "/start-core.sh"]
    expose:
      - 3003
  app:
    volumes:
      - ./deploy/start-with-frontend.sh:/start.sh